controller_joint_names: ['', 'leg1_1_joint', 'leg1_2_joint', 'leg1_3_joint', 'leg2_1_joint', 'leg2_2_joint', 'leg2_3_joint', 'leg3_1_joint', 'leg3_2_joint', 'leg3_3_joint', 'leg4_1_joint', 'leg4_2_joint', 'leg4_3_joint', ]
